sudo: required

env:
  - VERSION=latest
  - VERSION=0.7.2 URL=http://xenia.sote.hu/ftp/mirrors/www.apache.org/zeppelin/zeppelin-0.7.2/zeppelin-0.7.2-bin-all.tgz
  - VERSION=0.7.1 URL=http://xenia.sote.hu/ftp/mirrors/www.apache.org/zeppelin/zeppelin-0.7.1/zeppelin-0.7.1-bin-all.tgz
  - VERSION=0.7.0 URL=http://xenia.sote.hu/ftp/mirrors/www.apache.org/zeppelin/zeppelin-0.7.0/zeppelin-0.7.0-bin-all.tgz

services:
   - docker

script:
   - make build

after_success:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
   - make deploy
